# site settings

title: Amir Talakoob
description: Projects and CV
taglong: Webpage for projects and online CV
tagshort: Projects and CV
url: https://amirtalakoob.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/amirtalakoob/amirtalakoob.github.io

# author settings

author:
  name: Amir Talakoob
  email: amirtalakoob@csus.edu
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: AmirTalakoob
  instagram: amir__talakoob
  linkedin: amirtalakoob

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
